# Generated by Django 4.2 on 2023-04-14 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_item_category_item_description_item_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='static/images'),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('SH', 'Shirts'), ('TR', 'Trousers'), ('FW', 'Footwears'), ('OT', 'Others'), ('WT', 'Watches'), ('GT', 'Gadgets')], max_length=2),
        ),
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('secondary', 'Top'), ('primary', 'Trending'), ('danger', 'New')], max_length=15),
        ),
    ]
